// <auto-generated />
using System;
using IsArama.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsArama.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsArama.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yazılım Geliştirme"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Veri Bilimi & Yapay Zeka"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Siber Güvenlik"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sistem & Ağ Yönetimi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "UI/UX & Tasarım"
                        },
                        new
                        {
                            Id = 6,
                            Name = "DevOps & Cloud"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Oyun Geliştirme"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Muhasebe"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Finans & Bankacılık"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Denetim & Vergi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sigortacılık"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Satış & Satış Temsilcisi"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Dijital Pazarlama"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Marka & İletişim"
                        },
                        new
                        {
                            Id = 15,
                            Name = "E-ticaret"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Sosyal Medya Yönetimi"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Makine Mühendisliği"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Elektrik & Elektronik Mühendisliği"
                        },
                        new
                        {
                            Id = 19,
                            Name = "İnşaat & İnşaat Mühendisliği"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Endüstri Mühendisliği"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Kimya Mühendisliği"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Biyomedikal Mühendisliği"
                        },
                        new
                        {
                            Id = 23,
                            Name = "İnsan Kaynakları"
                        },
                        new
                        {
                            Id = 24,
                            Name = "İdari İşler & Sekreterlik"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Genel Müdürlük & Üst Yönetim"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Doktor & Uzman Hekim"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Hemşire & Sağlık Personeli"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Eczacılık"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Diş Hekimliği"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Psikoloji & Danışmanlık"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Öğretmenlik"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Akademik & Araştırma"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Özel Ders & Eğitmenlik"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Çocuk Gelişimi & Bakım"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Lojistik & Tedarik Zinciri"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Depo & Ambar"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Şoför & Kurye"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Üretim & İmalat"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Kalite Kontrol"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Müşteri Hizmetleri"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Çağrı Merkezi"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Teknik Destek"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Hukuk & Avukatlık"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Kamu & Devlet"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Askerlik & Güvenlik"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Gazetecilik & İçerik"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Grafik Tasarım"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Fotoğrafçılık & Video"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Mimarlık & İç Mimarlık"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Turizm & Otelcilik"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Aşçılık & Mutfak"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Garsonluk & Servis"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Perakende & Mağazacılık"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Moda & Tekstil"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Part-time & Yarı Zamanlı"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Staj & Yeni Mezun"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Uzaktan Çalışma"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Freelance"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Diğer"
                        });
                });

            modelBuilder.Entity("IsArama.Data.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("IsArama.Data.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("IsArama.Data.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://www.kariyer.net",
                            IsActive = true,
                            Name = "Kariyer.net"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://www.eleman.net",
                            IsActive = true,
                            Name = "Eleman.net"
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://www.yenibiris.com",
                            IsActive = true,
                            Name = "Yenibiris.com"
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://www.secretcv.com",
                            IsActive = true,
                            Name = "Secretcv.com"
                        },
                        new
                        {
                            Id = 5,
                            BaseUrl = "https://www.iskur.gov.tr",
                            IsActive = true,
                            Name = "İŞKUR"
                        },
                        new
                        {
                            Id = 6,
                            BaseUrl = "https://www.sahibinden.com",
                            IsActive = true,
                            Name = "Sahibinden.com"
                        },
                        new
                        {
                            Id = 7,
                            BaseUrl = "https://ilan.memurlar.net",
                            IsActive = true,
                            Name = "Memurlar.net"
                        },
                        new
                        {
                            Id = 8,
                            BaseUrl = "https://tr.indeed.com",
                            IsActive = true,
                            Name = "Indeed TR"
                        },
                        new
                        {
                            Id = 9,
                            BaseUrl = "https://www.adzuna.com.tr",
                            IsActive = true,
                            Name = "Adzuna TR"
                        },
                        new
                        {
                            Id = 10,
                            BaseUrl = "https://jooble.org/tr",
                            IsActive = true,
                            Name = "Jooble TR"
                        });
                });

            modelBuilder.Entity("IsArama.Data.Entities.Job", b =>
                {
                    b.HasOne("IsArama.Data.Entities.Category", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsArama.Data.Entities.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsArama.Data.Entities.Source", "Source")
                        .WithMany("Jobs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("IsArama.Data.Entities.Category", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("IsArama.Data.Entities.Company", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("IsArama.Data.Entities.Source", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
